[variables]
NIXPACKS_PYTHON_VERSION = "3.9"

[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.virtualenv"]

[phases.install]
cmds = [
    "echo '🚀 NIXPACKS: Installing Python dependencies...'",
    "python --version",
    "which python",
    "python -c 'import sys; print(sys.executable)'",
    "# Create virtual environment to avoid externally-managed-environment error",
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "/opt/venv/bin/python -m pip install --upgrade pip",
    "/opt/venv/bin/python -m pip install -r requirements-railway.txt",
    "echo '✅ NIXPACKS: Dependencies installed successfully'"
]

[phases.build]
cmds = [
    "echo '🔧 NIXPACKS: Building application...'",
    "source /opt/venv/bin/activate",
    "/opt/venv/bin/python -c \"import sys; print('Python version: ' + sys.version)\"",
    "/opt/venv/bin/python -c \"import os; print('discourse_posts.json exists: ' + str(os.path.exists('discourse_posts.json')))\"",
    "/opt/venv/bin/python -c \"from railway_search_engine import RailwaySearchEngine; print('Railway search engine import successful')\"",
    "/opt/venv/bin/python -c \"import sklearn, numpy, requests; print('Core dependencies imported successfully')\"",
    "/opt/venv/bin/python -c \"import fastapi, uvicorn; print('FastAPI and uvicorn imported successfully')\"",
    "echo '✅ NIXPACKS: Build completed successfully'"
]

[start]
cmd = "/opt/venv/bin/python -m uvicorn main-railway:app --host 0.0.0.0 --port $PORT"